name: Deploy to EC2

on:
  push:
    branches:
      - main
env:
  DOCKER_IMAGE: ghcr.io/sangddong/github-actions-auto
  VERSION: ${{github.sha}}
  NAME: go_cicd
  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
  PORT: ${{ secrets.PORT }}
  CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  # 'registry', 'username', 'password', 'ecr', 'logout']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          path: /tmp/.buildx-cache
          key: ${{runner.os}}-buildx-${{env.VERSION}}
          restore-keys: |
            ${{runner.os}}-buildx-

      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GHCR_TOKEN}}
          
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{steps.buildx.outputs.name}}
          push: true
          tags: ${{env.DOCKER_IMAGE}}
          
  deploy:
    needs: build
    name: Deploy
    runs-on: [self-hosted, label-go]
    steps:
      - name: Login to ghcr
        uses: docker/login-action@v1
        with: 
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GHCR_TOKEN}}
      - name: Docker run
        run: |
          sudo docker stop ${{ env.NAME }} || true
          sudo docker rm ${{ env.NAME }} || true
          sudo docker rmi ${{ env.DOCKER_IMAGE }}:latest || true
          sudo docker run -d -p 80:3000 \
            --name ${{ env.NAME }} \
            --restart always \
            -e JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
            -e PORT=${{ secrets.PORT }} \
            -e CORS_ORIGIN=${{ secrets.CORS_ORIGIN }} \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            ${{ env.DOCKER_IMAGE }}:latest
