name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build application
      run: npm run build

    - name: Deploy to EC2
      env:
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        PORT: ${{ secrets.PORT }}
        CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        ssh -o StrictHostKeyChecking=no -i <(echo "$EC2_SSH_KEY") $EC2_USER@$EC2_HOST << 'EOF'
          cd /path/to/your/app
          git pull origin main
          npm install
          npm run build
          export JWT_SECRET_KEY=$JWT_SECRET_KEY
          export PORT=$PORT
          export CORS_ORIGIN=$CORS_ORIGIN
          export DATABASE_URL=$DATABASE_URL
          pm2 restart all
        EOF

